### ISSUE TITLE
CSS知识点总结

### ISSUE THREAD

**Issue by gyk0818** [gyk0818/frontEnd#1]
## 目录
1. 选择器
2. CSS三大特性
3. flex布局
4. transform
5. animation（动画）
6. 页面元素隐藏
7. 盒模型
8. 垂直、水平居中
9. BFC IFC float
10. 边距重叠
11. px、em和rem的区别
12. 绝对定位
13. CSS性能加速

**Comment by gyk0818** [comment]
## 选择器
### 种类
* 基本选择器
    * 标签名
    * 类名
    * ID
    * 属性
* 伪类选择器（CSS伪类是用来添加一些选择器的特殊效果）
    * 结构伪类 `:first-child | :first-of-type(n) | :hover`
    * 伪元素 `::before | ::after`
* 组合选择器
    * 相邻兄弟 `A + B`
    * 普通兄弟 `A ~ B`
    * 子选择器 `A > B`
    * 后代选择器 `A B`

### 示例
```css
// 属性选择器
// 匹配包含title属性的a标签 => <a title>
a[title] {
    color: purple;
} 

// 结构伪类
// 选择所有p元素的最后一个子元素
p:last-child {
}

// +标识符：介于两个选择器之间，当第二个选择器匹配的元素紧跟着第一个元素后面并且它们都是同一个父亲
// A元素：.box1 div:first-of-type
// B元素：div
// 匹配紧跟着A的B
.box1 div:first-of-type+div { 
    color: red; 
}
```

### 应用场景
组合选择器可以用于：hover伪类操纵自己包含的子元素及以外的元素，例如：
```html
<div id='a'>元素1
  <div id='b'>元素2</div>
</div>
<div id='c'>元素3
  <div id='b'>元素2</div>
</div>
<div>同级元素1</div>
<div>同级元素2</div>
<div>同级元素3</div>
</body>
```

```css
#a:hover > #b{....}    
#a:hover ~ div{....} // 鼠标停留在a元素的时候让所有同层级元素有某某样式
// 防止选择器层级替换了下面的样式
#a:hover + #c{....} // 鼠标停留在a元素的时候让同层级中的c元素有某某样式
#a:hover + #c > #b{....} //  鼠标停留在a元素的时候让同层级中的c元素下的b元素有某某样式
```

**Comment by gyk0818** [comment]
## CSS三大特性
### 层叠性

> 层叠性是指多种CSS样式的叠加。如果一个属性通过两个**相同选择器**设置到同一个元素上，那么这个时候一个属性就会将另一个属性层覆盖掉

**原则**：
- 样式冲突，遵循的原则是就近原则。 那个样式离着结构近，就执行那个样式。
- 样式不冲突，不会层叠

### 继承性
> 子标签会继承父标签的某些样式，如文本颜色和字号。
注意：在CSS的继承中不仅仅是儿子可以继承，**只要是后代都可以继承**

常用的可继承的属性：字体系列（font-size、font-family、color）、阴影（box-shadow、text-shadow）、visibility等

对于天生自带的继承属性我们可以控制它是否需要继承：
- `inherit`：被应用属性继承父级的该属性（默认就是该值）
- `initial`：初始化，把应用属性初始为它默认的样式，并且排除继承的干扰（默认会继承的属性也不在默认继承，而是表现出没有任何设置时候的默认样式）
- `unset`：意思是恢复其原本的继承方式。对`color`属性而言，就相当于`inherit`；而对于诸如`border`这样默认不继承的属性，就相当于`initial`
- `revert`：效果等同于`unset`且浏览器支持有限，这里不做演示

**继承的属性的权重是0**

### 优先级
定义CSS样式时，经常出现两个或更多选择器应用在同一元素上，此时，

- 选择器相同，则执行层叠性（后者覆盖前者)
- 选择器不同，就会出现优先级的问题。

权重计算公式：
- !important 优先级最高
- 行内 : 1,0,0,0
- ID : 0,1,0,0
- 类、结构伪类 : 0,0,1,0
- 标签、伪元素 : 0,0,0,1
- 继承、* : 0,0,0,0

**值从左到右，左面的最大，一级大于一级，数位之间没有进制，级别之间不可超越。**

**Comment by gyk0818** [comment]
## flex布局

> 采用flex布局的元素称为容器，容器内的子元素称为项目
容器默认存在两根轴，水平的主轴和垂直的交叉轴

- flex-direction：设置主轴的方向（即项目的排列方向）
- justify-content：设置主轴上的子元素对齐方式
- flex-wrap：设置子元素是否换行
- align-content：定义了多根轴线的对齐方式。如果项目只有一根轴线，该属性不起作用。
- align-items：设置交叉轴上的子元素排列方式
- flex-flow：复合属性，相当于同时设置了 flex-direction 和 flex-wrap

**Comment by gyk0818** [comment]
## transform
### 前置属性

- transform-origin：用于指定元素变形的中心点
- transform-style：用于指定变换效果是2D还是3D
- perspective：指定3D的视距
- perspective-origin：设置视距的基点
- backface-visibility：是否可以看见3D舞台的背面，默认值visible表示背面可见

### 2D变形
translate位移，scale缩放，rotate旋转，skew扭曲，matrix矩阵

### 3D变形
3D变形有translate3d位移，scale3d缩放，rotate3d旋转， matrix3d矩阵。（注意skew扭曲是没有3D的）。3D的用法和2D差不多，只不过多了个Z轴的值而已

**Comment by gyk0818** [comment]
## animation
> 动画(animation)是 CSS3 中最具颠覆性的特征之一，可通过设置多个节点来精确的控制一个或者一组动画，从而实现复杂的动画效果, 先定义动画在调用定义好的动画

### 动画序列
> 0% 是动画的开始，100 % 是动画的完成，这样的规则就是动画序列

- 在 @keyframs 中规定某项 CSS 样式，就由创建当前样式逐渐改为新样式的动画效果
- 动画是使元素从一个样式逐渐变化为另一个样式的效果，可以改变任意多的样式任意多的次数
- 用百分比来规定变化发生的时间，或用 from 和 to，等同于 0% 和 100%

```css
@keyframes move{
	0% {
		transform: translate(0px)
	}
	form {
		transform: translate(0px)
	}
	
	100% {
		transform: translate(500px, 0)
	}
	to {
		transform: translate(500px, 0)
	}
}

```

**Comment by gyk0818** [comment]
## 页面元素隐藏

- `opacity:0` 本质上是将元素的透明度设置为0，看起来隐藏了，但是依然占据空间可以交互，不一定会引起重绘
- `visibility:hidden` 设置元素不可见，占据空间但是不能交互，会引起重绘
- `overflow:hidden` 隐藏元素溢出的部分，但是占据空间且不可交互
- `display:none` （定义建立布局时元素生成的显示框类型）彻底隐藏元素，元素从文档流消失，不占据空间也不能交互，也不影响布局，会引起重排和重绘
- `z-index:-9999` 将层级放到底部，这样就被覆盖了，看起来隐藏了
- `transform:scale(0,0)` 平面交换，将元素缩放为0，但是依然占据空间，不可交互

**Comment by gyk0818** [comment]
## 盒模型
![image](https://user-images.githubusercontent.com/71056773/97417375-91d31d80-1942-11eb-919a-a80982954db3.png)

- 标准盒模型：width和height不包含border和padding，只包含内容content
- IE盒模型：width和height包含border和padding
- 使用box-sizing来设置：content-box（标准盒模型）、border-box（IE盒模型）
- **盒模型和margin没有关系，这个问题我犯错过很多次了**

**Comment by gyk0818** [comment]
## 垂直、水平居中
### 水平居中
```css
// 行内元素
span{
  text-align:center;
}
// 块元素
div{
  margin:0 auto;
}
// 多个块元素水平居中
.father{
  text-align:center
}
.child{
  display:inline-block;
}
// flexbox解法
.father{
  justify-content:center;
  display:flex;
}
```

### 垂直居中
```css
// 已知高度
// 方法1：绝对定位+负外边距
#container{
    position:relative;
    width:300px;
    height:300px;
}
#center{
    width:100px;
    height:100px;
    position:absolute;
    top:50%;
    left:50%;
    margin:-50px 0 0 -50px;
}
// 方法2：绝对定位+margin
#container{
    position:relative;
    width: 300px;
    height: 300px;
}
#center{
    position:absolute;
    width: 50%;
    height: 30%;
    top:50%;
    left:50%;
    margin: -15% 0 0 -15%;
}
// 方法3：绝对定位+margin:auto
#container{
    position:relative;
    width: 300px;
    height: 300px;
}
#center{
    position:absolute;
    width: 50%;
    height: 30%;
    top:0;
    bottom:0;
    right:0;
    left:0;
    margin:auto;
}

// 未知宽高
// 方法1：绝对定位和transform
#box{
    width: 300px;
    height:300px;
    position:relative;
}
#child{
    position:absolute;
    top:50%;
    transform:translate(0,-50%);
}
// 方法2：flex布局
#box{
    width: 300px;
    height:300px;
    display: flex;
    align-items:center;
}
```
